require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
  TargetRailsVersion: 7.1

Metrics/MethodLength:
  Max: 15

RSpec/ExampleLength:
  Max: 10

RSpec/VerifiedDoubles:
  Exclude:
    - spec/services/webhooks/authorizators/stripe_spec.rb
    - spec/services/webhooks/processors/stripe/*.rb
    - spec/services/webhooks/processors/stripe_spec.rb

Style/Documentation:
  Enabled: false
