require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
  TargetRailsVersion: 7.1

Style/Documentation:
  Enabled: false